# 09 — Export for Overleaf (policy §4): numbers.tex with \newcommand macros, booktabs
# tables (\input-ready) and vector/PNG figures. Every number in the article comes from
# here; nothing is typed by hand. At the feasibility stage this exports only pilot
# DIAGNOSTICS (clearly labelled), so the skeleton compiles; phase-1 estimates replace them.
for (f in list.files("R", full.names = TRUE)) source(f)
cfg <- load_config(); ensure_dirs(cfg)
out <- "outputs/overleaf"; for (d in c(out, file.path(out, "tables"), file.path(out, "figures"))) dir.create(d, showWarnings = FALSE, recursive = TRUE)
log <- make_logger("outputs/logs/09_export_overleaf.log")

fmt_int <- function(x) format(round(x), big.mark = ",", scientific = FALSE, trim = TRUE)
fmt_brl <- function(x) format(round(x), big.mark = ",", scientific = FALSE, trim = TRUE)
macro <- function(name, value) sprintf("\\newcommand{\\%s}{%s}", name, value)
tex_escape <- function(x) gsub("([%&_#])", "\\\\\\1", x)

lines <- c(sprintf("%% numbers.tex — GENERATED by scripts/09_export_overleaf.R on %s; do not edit.", format(Sys.time())),
           sprintf("%% Stage: %s. Macros prefixed 'pilot' are diagnostics, not results.", cfg$project$stage))

# --- Source counts (from 01) ---------------------------------------------------------------
chk <- if (file.exists("outputs/diagnostics/01_source_checks.csv")) utils::read.csv("outputs/diagnostics/01_source_checks.csv") else NULL
if (!is.null(chk)) {
  tc <- chk$detail[chk$id == "tjdft_count"]
  yrs <- regmatches(tc, gregexpr("(\\d{4})=\\s*([\\d\\.]+)", tc, perl = TRUE))[[1]]
  for (y in yrs) { k <- sub("=.*", "", y); v <- gsub("\\.", "", sub(".*=\\s*", "", y)); lines <- c(lines, macro(paste0("tjdftHits", k), fmt_int(as.numeric(v)))) }
}

# --- Pilot diagnostics (from 02/03) --------------------------------------------------------
if (file.exists(cfg$paths$db)) {
  con <- db_connect(cfg, read_only = TRUE); on.exit(DBI::dbDisconnect(con, shutdown = TRUE), add = TRUE)
  n <- DBI::dbGetQuery(con, "SELECT count(*) n, count(inteiro_teor) nft, min(data_julgamento) d0, max(data_julgamento) d1 FROM acordaos")
  lines <- c(lines, macro("pilotDecisions", fmt_int(n$n)), macro("pilotWithFullText", fmt_int(n$nft)),
             macro("pilotWindowStart", as.character(n$d0)), macro("pilotWindowEnd", as.character(n$d1)))
  if (DBI::dbExistsTable(con, "value_mentions")) {
    m <- DBI::dbGetQuery(con, "SELECT count(*) n, count(DISTINCT uuid) nd FROM value_mentions")
    lines <- c(lines, macro("pilotMentions", fmt_int(m$n)), macro("pilotDecisionsWithMention", fmt_int(m$nd)))
  }
  # Table: decisions by base/subbase (pilot)
  bb <- DBI::dbGetQuery(con, "SELECT base, subbase, count(*) AS n FROM acordaos GROUP BY 1,2 ORDER BY n DESC")
  tab <- c("% GENERATED — pilot sample composition (diagnostic)",
           "\\begin{table}[t]\\centering\\caption{Pilot sample by document base (TJDFT, diagnostic)}\\label{tab:pilot_base}",
           "\\begin{tabular}{llr}\\toprule Base & Sub-base & N \\\\ \\midrule",
           sprintf("%s & %s & %s \\\\", tex_escape(bb$base), tex_escape(bb$subbase), fmt_int(bb$n)),
           "\\bottomrule\\end{tabular}\\end{table}")
  writeLines(tab, file.path(out, "tables", "tab_pilot_base.tex"))
}
cov_f <- "outputs/diagnostics/03_extraction_coverage.csv"
if (file.exists(cov_f)) {
  cov <- utils::read.csv(cov_f)
  nm <- c("decisions" = "pilotCovDecisions", "with any R$ mention" = "pilotCovAnyMention",
          "with R$ in ementa" = "pilotCovEmenta", "with moral-context mention" = "pilotCovMoral",
          "award picked from ementa" = "pilotCovAwardEmenta", "award picked from any section" = "pilotCovAwardAny")
  for (i in seq_len(nrow(cov))) if (cov$metric[i] %in% names(nm)) {
    lines <- c(lines, macro(nm[[cov$metric[i]]], fmt_int(cov$n[i])), macro(paste0(nm[[cov$metric[i]]], "Pct"), sprintf("%.1f", 100 * cov$share[i])))
  }
  tab <- c("% GENERATED — extractor coverage on the pilot (diagnostic)",
           "\\begin{table}[t]\\centering\\caption{Rule-based extractor coverage on the pilot month (diagnostic, unvalidated)}\\label{tab:pilot_coverage}",
           "\\begin{tabular}{lrr}\\toprule Metric & N & Share (\\%) \\\\ \\midrule",
           sprintf("%s & %s & %.1f \\\\", tex_escape(cov$metric), fmt_int(cov$n), 100 * cov$share),
           "\\bottomrule\\end{tabular}\\end{table}")
  writeLines(tab, file.path(out, "tables", "tab_pilot_coverage.tex"))
}
ht_f <- "outputs/diagnostics/03_harm_type_distribution.csv"
if (file.exists(ht_f)) {
  ht <- utils::read.csv(ht_f)
  tab <- c("% GENERATED — harm-type dictionary hits on the pilot (diagnostic)",
           "\\begin{table}[t]\\centering\\caption{Harm-type dictionary classification, pilot month (diagnostic)}\\label{tab:pilot_harm}",
           "\\begin{tabular}{lr}\\toprule Harm type & N \\\\ \\midrule",
           sprintf("%s & %s \\\\", tex_escape(gsub("_", " ", ht$harm_type)), fmt_int(ht$Freq)),
           "\\bottomrule\\end{tabular}\\end{table}")
  writeLines(tab, file.path(out, "tables", "tab_pilot_harm.tex"))
}
# Figure: distribution of picked (unvalidated) awards, if any
q_f <- "outputs/diagnostics/03_per_decision_diagnostics.csv"
if (file.exists(q_f) && requireNamespace("ggplot2", quietly = TRUE)) {
  d <- utils::read.csv(q_f); a <- d$award_any[!is.na(d$award_any) & d$award_any > 0]
  if (length(a) > 10) {
    p <- ggplot2::ggplot(data.frame(a = a), ggplot2::aes(x = a)) + ggplot2::geom_histogram(bins = 40) +
      ggplot2::scale_x_log10(labels = function(x) format(x, big.mark = ",", scientific = FALSE)) +
      ggplot2::labs(x = "Picked award (BRL, log scale) — pilot, unvalidated extractor", y = "Decisions") + ggplot2::theme_minimal()
    ggplot2::ggsave(file.path(out, "figures", "fig_pilot_award_hist.pdf"), p, width = 6.5, height = 4)
    ggplot2::ggsave(file.path(out, "figures", "fig_pilot_award_hist.png"), p, width = 6.5, height = 4, dpi = 200)
    lines <- c(lines, macro("pilotPickedAwards", fmt_int(length(a))), macro("pilotMedianPickedBRL", fmt_brl(stats::median(a))))
  }
}

writeLines(lines, file.path(out, "numbers.tex"))
writeLines(utils::capture.output(utils::sessionInfo()), "outputs/logs/sessionInfo.txt")
log(sprintf("numbers.tex: %d macros; tables: %d; figures: %d", sum(grepl("newcommand", lines)),
            length(list.files(file.path(out, "tables"))), length(list.files(file.path(out, "figures")))))
